
#General Config Section. See https://srpc.fdd-docs.com/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = "1379569487128297554"
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Allow using local image files, as RPC icons
	rpcImageServer = false
	#The URL of the RPC image server that will be used for local images. Restart required when changed
	rpcImageServerUrl = "https://rpcavatar.firstdark.dev"
	#Internal Version Number. NO TOUCHY!
	version = 26

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[init.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Starfell is booting..."
		#The second line of text under the app name
		state = "Game Starting..."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}} loves quality!"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[main_menu.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}} is resting in"
		#The second line of text under the app name
		state = "the main menu..."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}} loves quality!"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[server_list.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}} is looking for a server..."
		#The second line of text under the app name
		state = "Searching for friends..."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}} loves quality!"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[realms_list.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}} is looking for a realm..."
		#The second line of text under the app name
		state = "Browsing realms..."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}} loves quality!"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[join_game.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}} is joining a game..."
		#The second line of text under the app name
		state = "Joining Game..."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}} loves quality!"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[single_player.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}} is exploring"
		#The second line of text under the app name
		state = "the {{world.name}}"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}} loves quality!"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[multi_player.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Playing on {{server.name}} with {{server.players.count}} players"
		#The second line of text under the app name
		state = "Playing with friends, probably..."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}} loves quality!"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[realms.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Playing on {{realm.name}}"
		#The second line of text under the app name
		state = "Playing on a Realm"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Paused Event
[paused]
	#Enable/Disable the Pause Event
	enabled = false

	#List of RPCs that will be displayed at random
	[[paused.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Resting in the pause"
		#The second line of text under the app name
		state = "menu..."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}} loves quality!"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#Fallback event for disabled events
[generic]

	#List of RPCs that will be displayed at random
	[[generic.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Exploring the world"
		#The second line of text under the app name
		state = "of Starfell."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["valcon_logo_big"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "Starfell: Rise of The Valcon Knight is a prequel to a Medieval RPG modpack developed by IvqryDev in Starlight Studios. Coming soon to Modrinth!"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["valcon_logo_small"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{game.mods}} mods installed"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "overworld"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "{{player.name}} is exploring The Overworld"
			#The second line of text under the app name
			state = "Playing in {{world.name}}"
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["valcon_logo_big"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "In the Overworld"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["valcon_logo_small"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{player.name}} loves quality!"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"
			#List of buttons (max 2) to show on the RPC
			buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_nether"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "{{player.name}} is exploring The Nether"
			#The second line of text under the app name
			state = "Playing in {{world.name}}"
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["valcon_logo_big"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "In the Nether"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["valcon_logo_small"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{player.name}} loves quality!"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"
			#List of buttons (max 2) to show on the RPC
			buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_end"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "{{player.name}} is exploring The Shadow Islands"
			#The second line of text under the app name
			state = "Playing in {{world.name}}"
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["valcon_logo_big"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "In the Shadow Islands"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["valcon_logo_small"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{player.name}} loves quality!"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"
			#List of buttons (max 2) to show on the RPC
			buttons = []

