["Boss Health"]
	"Knight Health" = 100.0
	#Max Health : 1024
	"Sandworm Health" = 200.0
	"Yeti Health" = 250.0
	"Dragon Health" = 250.0

["Boss Armor"]
	"Knight Armor" = 0.0
	#Max Armor : 30
	"Sandworm Armor" = 20.0
	"Yeti Armor" = 5.0
	"Dragon Armor" = 25.0

["Base Boss Damages"]
	#Not all damages sources depends on this variable !
	"Sandworm Damage" = 11.0
	"Yeti Damage" = 8.0
	"Knight Damage" = 9.0
	"Dragon Damage" = 15.0

["Gameplay Changes"]
	"Can players use the Roll ability" = false
	"How many roll charges does the player have by default?" = 2
	"How many ticks does it take for a roll to cooldown? (20 ticks is 1 second)" = 40
	"How many additional ticks should each roll above 1 take to cooldown? (20 ticks is 1 second)" = 20
