# Maximum distance from campfire
# default: 3
distance = 8
# Maximum duration of effect
# default: 5
duration = 5
# Amplifier of effect
# default: 0
amplifier = 0

# What effects should be applied
[effects]
	"minecraft:campfire" = "minecraft:regeneration"
	"minecraft:soul_campfire" = "minecraft:regeneration"
