["The Garden Awakens"]
	#allow features from 'The Garden Awakens' to be obtainable through wandering traders
	pale_trades = false
	#allow resin to be obtainable from creaking hearts
	resin = true
	#allow resin to appear on chests at woodland mansions
	resin_loot = true
	#allow creakings to spawn from creaking hearts
	creaking = true
	#allow the pale garden to generate in the overworld
	pale_garden = true
	#creaking heart trail particle color (gray by default)
	creaking_particle_color = 6250335
	#creaking heart trail particle reverse color (orange by default)
	creaking_particle_reverse_color = 16545810

["Bundles of Bravery"]
	#toggle the updated controls and UI for bundles
	has_updated_bundles = false
	#allow bundles to appear on chests at villages
	bundle_loot = true

["Spring to Life"]
	#allow features from 'Spring to Life' to be obtainable through wandering traders
	spring_trades = false
	#allow bushes to generate in the overworld
	bushes = false
	#allow firefly bushes to generate in the overworld
	firefly_bushes = false
	#allow dry grass to generate in the overworld
	dry_grass = false
	#allow variants for pigs, cows and chickens to generate
	farm_animal_variants = false
	#allow leaf litter to generate in the overworld
	leaf_litter = false
	#allow wildflowers to generate in the overworld
	wildflowers = true
	#allow fallen trees to generate in the overworld
	fallen_trees = true
	#allow cactus flowers to generate
	cactus_flowers = true
	#allow wolfs to have variants for their sounds
	wolf_sound_variants = true
	#allow camels to spawn outside of villages
	camel_spawns = true
	#allow lodestones to appear on chests at ruined portals
	lodestone_loot = true

["Chase the Skies"]
	#allows ghasts drop the tears music disc
	tears_music_disc = false
	#allow dried ghasts to be obtainable through nether fossils and piglin bartering
	dried_ghasts = true
	#toggle whether leashes drop their connections when boosting with a firework rocket
	leash_drop_connections = true
	#apply a modifier to the speed of happy ghasts when ridden, 1.0 is default speed
	happy_ghast_speed_modifier = 1.0

["Hot as Lava"]
	#allows chicken jockeys to drop the lava chicken music disc
	lava_chicken_music_disc = false

[Debug]
	#toggle debug features
	debug = false
