[blocks]
	"Wooden chests" = false
	"Leaf piles" = false
	"Wooden boards" = false
	"Wooden beehives" = false
	"Wooden bookshelves" = false
	"Wooden ladders" = false
	#If the vanilla Chest can be crafted from mixing woods or woods without a chest variant
	"Mixed chest crafting" = false
	Sawmill = true

[generation]
	#If variant bookshelves replace bookshelves in Villages
	"Wooden bookshelves in Villages" = false
	#If variant chests replace chests in Villages
	"Wooden chests in Villages" = false
	#If variant ladders replace ladders in Villages
	"Wooden ladders in Villages" = true
