# Don't change this! Version used to track needed updates.
version = 0
foxTamingItems = [
    "minecraft:glow_berries"
]
foxBreedingItems = [
    "minecraft:sweet_berries"
]
itemsRestrictedToPick = [  ]
foxesAttackWithOwner = true
foxesTameDirectly = true
foxesTamingChance = 1.0
foxesCanIgnoreMobGriefingRule = false
foxesTrustOnBorn = true
untamedFoxesCanBeTempted = false
untamedWolvesAttackTamedFoxes = false